version: '3.8'

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DB_URL=postgres://medicue_user:medicue_password@db:5432/medicue?sslmode=disable
      - RUN_MIGRATIONS=true
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./logs:/root/logs
    restart: unless-stopped
    networks:
      - medicue-network

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: medicue
      POSTGRES_USER: medicue_user
      POSTGRES_PASSWORD: medicue_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./adapters/db/migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U medicue_user -d medicue"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - medicue-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - medicue-network

volumes:
  postgres_data:
  redis_data:

networks:
  medicue-network:
    driver: bridge
