# fly.toml app configuration file generated for medicue
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

app = "medicue"
primary_region = "ord" # Chicago - change to your preferred region
kill_signal = "SIGINT"
kill_timeout = "5s"

[experimental]
  auto_rollback = true

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  # Set to false to skip automatic migrations on startup if needed
  RUN_MIGRATIONS = "true"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 800

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/v1/health"
    protocol = "http"
    tls_skip_verify = false

    [http_service.checks.headers]
      Content-Type = "application/json"

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1

[metrics]
  port = 8080
  path = "/metrics"

# Restart policy
[restart]
  policy = "on-failure"

# Volume mounts for persistent data (if needed)
# [[mounts]]
#   source = "medicue_data"
#   destination = "/data"

# Process groups
[processes]
  app = "./main"

# Deploy configuration
[deploy]
  release_command = "./bin/migrate -path=adapters/db/migrations -database $DATABASE_URL up"
  strategy = "rolling"
  
  [[deploy.checks]]
    name = "health"
    type = "http"
    interval = "10s"
    timeout = "2s"
    grace_period = "5s"
    method = "get"
    path = "/v1/health"
    protocol = "http"
    tls_skip_verify = false

# Console configuration for debugging
[console]
  command = "/bin/sh"
