// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateEmailVerificationToken(ctx context.Context, arg CreateEmailVerificationTokenParams) (*EmailVerificationToken, error)
	// Create a Medical Record
	CreateMedicalRecord(ctx context.Context, arg CreateMedicalRecordParams) (*MedicalRecord, error)
	CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) error
	CreateUser(ctx context.Context, arg CreateUserParams) (*CreateUserRow, error)
	// Inserts a new diagnostic record into the diagnostic_centres table.
	Create_Diagnostic_Centre(ctx context.Context, arg Create_Diagnostic_CentreParams) (*DiagnosticCentre, error)
	// Create a diagnostic schedule
	Create_Diagnostic_Schedule(ctx context.Context, arg Create_Diagnostic_ScheduleParams) (*DiagnosticSchedule, error)
	// Deletes a diagnosticCentre only by the created_by.
	Delete_Diagnostic_Centre_ByOwner(ctx context.Context, arg Delete_Diagnostic_Centre_ByOwnerParams) (*DiagnosticCentre, error)
	Delete_Diagnostic_Schedule(ctx context.Context, arg Delete_Diagnostic_ScheduleParams) (*DiagnosticSchedule, error)
	Find_Nearest_Diagnostic_Centres_WhenRejected(ctx context.Context, arg Find_Nearest_Diagnostic_Centres_WhenRejectedParams) ([]*Find_Nearest_Diagnostic_Centres_WhenRejectedRow, error)
	GetEmailVerificationToken(ctx context.Context, arg GetEmailVerificationTokenParams) (*EmailVerificationToken, error)
	// Get a Medical Record
	GetMedicalRecord(ctx context.Context, arg GetMedicalRecordParams) (*GetMedicalRecordRow, error)
	// Get Medical Records
	// Retrieves a paginated list of medical records for a specific user, ordered by creation date (most recent first).
	GetMedicalRecords(ctx context.Context, arg GetMedicalRecordsParams) ([]*GetMedicalRecordsRow, error)
	GetPasswordResetToken(ctx context.Context, token string) (*PasswordResetToken, error)
	// Get an Uploader Medical Record
	// Retrieves a medical record by its ID and uploader ID.
	GetUploaderMedicalRecord(ctx context.Context, arg GetUploaderMedicalRecordParams) (*GetUploaderMedicalRecordRow, error)
	// Get Uploader Medical Records
	// Retrieves a paginated list of medical records uploaded by a specific uploader, explicitly ordered by creation date in descending order (most recent first).
	GetUploaderMedicalRecords(ctx context.Context, arg GetUploaderMedicalRecordsParams) ([]*GetUploaderMedicalRecordsRow, error)
	GetUser(ctx context.Context, id string) (*User, error)
	GetUserByEmail(ctx context.Context, email pgtype.Text) (*User, error)
	GetUsers(ctx context.Context, arg GetUsersParams) ([]*User, error)
	// Retrieves a single diagnostic record by its ID.
	Get_Diagnostic_Centre(ctx context.Context, id string) (*DiagnosticCentre, error)
	// GetDiagnosticCentreByManager
	Get_Diagnostic_Centre_ByManager(ctx context.Context, arg Get_Diagnostic_Centre_ByManagerParams) (*DiagnosticCentre, error)
	// GetADiagnosticCentreByOwner :one
	Get_Diagnostic_Centre_ByOwner(ctx context.Context, arg Get_Diagnostic_Centre_ByOwnerParams) (*DiagnosticCentre, error)
	// Get Diagnostic Schedule
	Get_Diagnostic_Schedule(ctx context.Context, arg Get_Diagnostic_ScheduleParams) (*DiagnosticSchedule, error)
	// Get Diagnostic Schedules
	Get_Diagnostic_Schedules(ctx context.Context, arg Get_Diagnostic_SchedulesParams) ([]*DiagnosticSchedule, error)
	Get_Diagnsotic_Schedule_By_Centre(ctx context.Context, arg Get_Diagnsotic_Schedule_By_CentreParams) (*DiagnosticSchedule, error)
	Get_Diagnsotic_Schedules_By_Centre(ctx context.Context, arg Get_Diagnsotic_Schedules_By_CentreParams) ([]*DiagnosticSchedule, error)
	// Retrieves the nearest diagnostic centres based on latitude and longitude.
	Get_Nearest_Diagnostic_Centres(ctx context.Context, arg Get_Nearest_Diagnostic_CentresParams) ([]*Get_Nearest_Diagnostic_CentresRow, error)
	// Retrieves all diagnostic records for a specific owner.
	List_Diagnostic_Centres_ByOwner(ctx context.Context, arg List_Diagnostic_Centres_ByOwnerParams) ([]*DiagnosticCentre, error)
	MarkEmailAsVerified(ctx context.Context, email pgtype.Text) error
	MarkEmailVerificationTokenUsed(ctx context.Context, arg MarkEmailVerificationTokenUsedParams) error
	MarkResetTokenUsed(ctx context.Context, id string) error
	// Retrieves all diagnostic records with pagination.
	Retrieve_Diagnostic_Centres(ctx context.Context, arg Retrieve_Diagnostic_CentresParams) ([]*DiagnosticCentre, error)
	// Searches diagnostic_centres by name with pagination.
	Search_Diagnostic_Centres(ctx context.Context, arg Search_Diagnostic_CentresParams) ([]*DiagnosticCentre, error)
	// SearchDiagnosticWith Doctor type
	Search_Diagnostic_Centres_ByDoctor(ctx context.Context, arg Search_Diagnostic_Centres_ByDoctorParams) ([]*DiagnosticCentre, error)
	// Uploader Update a Medical Record
	// Updates a medical record by uploader, allowing partial updates to fields. Only the uploader can update their own records. Updates the 'updated_at' timestamp.
	UpdateMedicalRecordByUploader(ctx context.Context, arg UpdateMedicalRecordByUploaderParams) (*MedicalRecord, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (*UpdateUserRow, error)
	UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) error
	// Updates a diagnostic centre by the owner.
	Update_Diagnostic_Centre_ByOwner(ctx context.Context, arg Update_Diagnostic_Centre_ByOwnerParams) (*DiagnosticCentre, error)
	// Update a diagnostic schedule
	Update_Diagnostic_Schedule(ctx context.Context, arg Update_Diagnostic_ScheduleParams) (*DiagnosticSchedule, error)
	Update_Diagnostic_Schedule_By_Centre(ctx context.Context, arg Update_Diagnostic_Schedule_By_CentreParams) (*DiagnosticSchedule, error)
}

var _ Querier = (*Queries)(nil)
