CREATE TYPE DOCTOR AS ENUM ('Female', 'Male');
CREATE TYPE available_tests AS ENUM (
  'BLOOD_TEST',
  'URINE_TEST',
  'X_RAY',
  'MRI',
  'CT_SCAN',
  'ULTRASOUND',
  'ECG',
  'EEG',
  'BIOPSY',
  'SKIN_TEST',
  'ALLERGY_TEST',
  'GENETIC_TEST',
  'IMMUNOLOGY_TEST',
  'HORMONE_TEST',
  'VIRAL_TEST',
  'BACTERIAL_TEST',
  'PARASITIC_TEST',
  'FUNGAL_TEST',
  'MOLECULAR_TEST',
  'TOXICOLOGY_TEST',
  'ECHO',
  'COVID_19_TEST',
  'OTHER',
  'BLOOD_SUGAR_TEST',
  'LIPID_PROFILE',
  'HEMOGLOBIN_TEST',
  'THYROID_TEST',
  'LIVER_FUNCTION_TEST',
  'KIDNEY_FUNCTION_TEST',
  'URIC_ACID_TEST',
  'VITAMIN_D_TEST',
  'VITAMIN_B12_TEST',
  'HEMOGRAM',
  'COMPLETE_BLOOD_COUNT',
  'BLOOD_GROUPING',
  'HEPATITIS_B_TEST',
  'HEPATITIS_C_TEST',
  'HIV_TEST',
  'MALARIA_TEST',
  'DENGUE_TEST',
  'TYPHOID_TEST',
  'COVID_19_ANTIBODY_TEST',
  'COVID_19_RAPID_ANTIGEN_TEST',
  'COVID_19_RT_PCR_TEST',
  'PREGNANCY_TEST'
);

CREATE TABLE IF NOT EXISTS diagnostic_centres (
  id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
  diagnostic_centre_name VARCHAR(255) NOT NULL,
  latitude DOUBLE PRECISION NULL,
  longitude DOUBLE PRECISION NULL,
  address JSONB NULL,
  contact JSONB NULL,
  doctors DOCTOR[] NOT NULL DEFAULT ARRAY['Male']::DOCTOR[],
  available_tests available_tests[] NOT NULL DEFAULT ARRAY['CT_SCAN']::available_tests[],
  created_by UUID NOT NULL REFERENCES users(id), -- diagnostic manager who created the centre
  admin_id UUID NOT NULL REFERENCES users(id),   -- admin assigned to the centre
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT NOW(),
  CHECK (latitude IS NULL OR (latitude >= -90 AND latitude <= 90)),
  CHECK (longitude IS NULL OR (longitude >= -180 AND longitude <= 180)),
  CHECK (address IS NULL OR jsonb_typeof(address) = 'object'),
  CHECK (contact IS NULL OR jsonb_typeof(contact) = 'object'),
  CHECK (created_at <= NOW()),
  CHECK (updated_at <= NOW()),
  CHECK (updated_at >= created_at),
  UNIQUE (diagnostic_centre_name, created_by, longitude, latitude, address)
);
