-- Drop the check constraint first
ALTER TABLE diagnostic_schedules DROP CONSTRAINT IF EXISTS valid_test_type_check;

-- Create the enum type
DROP TYPE IF EXISTS test_type;
CREATE TYPE test_type AS ENUM (
    'BLOOD_TEST', 'URINE_TEST', 'X_RAY', 'MRI', 'CT_SCAN', 'ULTRASOUND', 'ECG',
    'EEG', 'BIOPSY', 'SKIN_TEST', 'IMMUNOLOGY_TEST', 'HORMONE_TEST', 'VIRAL_TEST',
    'BACTERIAL_TEST', 'PARASITIC_TEST', 'FUNGAL_TEST', 'MOLECULAR_TEST', 'TOXICOLOGY_TEST',
    'ECHO', 'COVID_19_TEST', 'BLOOD_SUGAR_TEST', 'LIPID_PROFILE', 'HEMOGLOBIN_TEST',
    'THYROID_TEST', 'LIVER_FUNCTION_TEST', 'KIDNEY_FUNCTION_TEST', 'URIC_ACID_TEST',
    'VITAMIN_D_TEST', 'VITAMIN_B12_TEST', 'HEMOGRAM', 'COMPLETE_BLOOD_COUNT',
    'BLOOD_GROUPING', 'HEPATITIS_B_TEST', 'HEPATITIS_C_TEST', 'HIV_TEST',
    'MALARIA_TEST', 'DENGUE_TEST', 'TYPHOID_TEST', 'COVID_19_ANTIBODY_TEST',
    'COVID_19_RAPID_ANTIGEN_TEST', 'COVID_19_RT_PCR_TEST', 'PREGNANCY_TEST',
    'ALLERGY_TEST', 'GENETIC_TEST', 'OTHER'
);

-- Convert the column back to enum type
ALTER TABLE diagnostic_schedules ALTER COLUMN test_type TYPE test_type USING test_type::test_type;
