name: Go CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: medicue_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U postgres" --health-interval=10s --health-timeout=5s --health-retries=5

    env:
      DB_URL: postgres://postgres:postgres@localhost:5432/medicue_test?sslmode=disable

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Install dependencies
        run: go mod download

      - name: Install migration tools
        run: make setup

      - name: Run migrations
        run: |
          ./bin/migrate -path adapters/db/migrations -database "$DB_URL" up

      - name: Verify migration status
        run: |
          ./bin/migrate -path adapters/db/migrations -database "$DB_URL" version

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
